name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  # Run for every pushes to main and releases
  push:
    branches: [main, master]
  release:
    types: [published]

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            github::ropensci-review-tools/autotest
      - uses: ropensci-review-tools/pkgcheck-action@main
